#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Mismatch Sample Error-Attribution Analysis (PHQ-8)
==================================================
Module 13 of the DAIC-WOZ strict reanalysis.

This module operationalises the "why do models err?" question as a SMALL,
REPRODUCIBLE error-attribution analysis that must contain four ingredients:
  (1) mismatch samples (self-report vs interview-evidence disagreement),
  (2) error DIRECTION (underestimate / overestimate),
  (3) human attribution coding (R1-R6, two independent reviewers),
  (4) necessary controls (consistent high / consistent low groups A & B).

It is explicitly NOT a causal proof. The quantitative parts (four-group
error rates, error directions, association tests) are fully computed here
from frozen inputs. The human-attribution coding (R1-R6) is left as a
BLANK coding sheet for human reviewers — this script does NOT fabricate
attribution codes, and does NOT read or emit raw interview text.

Hard constraints (inherited from the strict reanalysis SPEC):
  - Read ONLY frozen input files (same paths as modules 11 / 12).
  - NEVER use any OOF probability as a feature for a new model.
  - ALL merges on `participant_id`.
  - All models fold-local (10x5 participant-level repeated CV).
  - Do NOT read any superseded 01-06 results.
  - Do NOT output raw interview text; the coding sheet carries only IDs +
    structured indicators, with free-text attribution columns left BLANK
    for human reviewers.

Outputs (8 files, all generated by this script):
  attribution_error_direction_table.csv   # Table 1 (quantitative, computed)
  attribution_direction_stats.csv         # Fisher test (mismatch vs consistent error rate)
  coding_pool_all.csv                     # full mismatch+complex-error pool (all rows)
  coding_sheet_selected.csv              # selected subset for full human coding (<=15/type)
  codebook.md                             # R1-R6 definitions + two-reviewer procedure
  attribution_analysis_summary.md         # narrative + Table 1 numbers
  run_manifest.json
  output_manifest_sha256.csv

NOTE: `aggregate_coding.py` is a COMPANION script provided in this directory
(runtime-independent of this generator). It is NOT an output of this script.
Run it AFTER human reviewers fill `coding_sheet_selected.csv` (columns r1_* / r2_*)
to produce Table 2 + Cohen's Kappa.

Author: strict reanalysis (2026-07-09)
"""

import os
import json
import hashlib
import warnings
from datetime import datetime
from pathlib import Path

import numpy as np
import pandas as pd
from scipy import stats as scipy_stats
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import roc_auc_score

warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore", category=UserWarning)

# ── Paths (SPEC-compliant, same BASE as modules 11 / 12) ─────────────────────
SCRIPT_DIR = Path(__file__).parent
BASE = SCRIPT_DIR.parent.parent
DOMAIN_COUNT_CSV = BASE / "04_c5_controls/domain_count/input.csv"
DOMAIN_PRESENCE_CSV = BASE / "04_c5_controls/domain_presence/input.csv"
SPLIT_CSV = BASE / "00_splits/repeated_5fold_splits_10x5.csv"
FROZEN_TURNS = BASE / "01_inputs/c4_turns_official142_frozen.csv"
STRICT_OOF_CSV = BASE / "10_source_importance/07_strict_joint_models/participant_oof_predictions.csv"
OUTDIR = SCRIPT_DIR

# ── Symptom domain definitions (must match modules 09 / 10 / 11 / 12) ─────────
DOMAIN_COLS = [
    "depressed_mood",
    "anhedonia_interest",
    "sleep_fatigue_energy",
    "appetite_weight",
    "self_worth_guilt",
    "concentration_psychomotor",
    "suicide_self_harm",
    "functioning_impairment",
    "mental_health_history",
    "protective_or_absent_symptom",
]

RANDOM_SEED = 20260705
LR_PARAMS = dict(
    penalty="l2", C=1.0, class_weight="balanced",
    solver="liblinear", max_iter=2000, random_state=RANDOM_SEED,
)
np.random.seed(RANDOM_SEED)

# ── Analysis parameters ──────────────────────────────────────────────────────
THRESHOLD = 0.5          # decision threshold for predicted class
PHQ_POS_CUT = 10         # PHQ-8 >= 10 defines self-report "high"
COVERAGE_PREDEF = 5      # pre-defined "high evidence" = >= 5 touched domains
DENSITY_PREDEF = 11      # pre-defined "high evidence" = >= 11 evidence pieces
# For THIS analysis, "text evidence high" is the union of the two pre-defined
# cut-offs (per the analysis SPEC): coverage >= 5 OR evidence_density >= 11.
# This is an operational definition, NOT a clinical diagnosis.
CODING_CAP_PER_TYPE = 15  # if a mismatch type has > this many erred cases, sample


# ═══════════════════════════════════════════════════════════════════════════
# UTILITY FUNCTIONS
# ═══════════════════════════════════════════════════════════════════════════
def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


# ═══════════════════════════════════════════════════════════════════════════
# DATA LOADING & VALIDATION (identical to module 12 — reused for SPEC parity)
# ═══════════════════════════════════════════════════════════════════════════
def load_and_validate():
    print("[LOAD] Loading frozen inputs...")
    dcount = pd.read_csv(DOMAIN_COUNT_CSV)
    dpres = pd.read_csv(DOMAIN_PRESENCE_CSV)
    frozen = pd.read_csv(FROZEN_TURNS)
    oof = pd.read_csv(STRICT_OOF_CSV)
    splits = pd.read_csv(SPLIT_CSV)

    errors = []

    g_score = frozen.groupby("participant_id")["paper_phq8_score"]
    if (g_score.nunique() > 1).any():
        errors.append("CRITICAL: paper_phq8_score not constant per participant")
    score_pp = g_score.first()
    label_pp = frozen.groupby("participant_id")["paper_label_phq8_ge10"].first()
    if not (score_pp >= 10).astype(int).equals(label_pp):
        errors.append("CRITICAL: label != (score>=10) for some participants")

    pid_score = frozen.groupby("participant_id").agg(
        phq8_score=("paper_phq8_score", "first"),
        label=("paper_label_phq8_ge10", "first"),
    ).reset_index()

    if not dcount["participant_id"].is_unique:
        errors.append("CRITICAL: duplicate participant_id in domain_count")
    if not dpres["participant_id"].is_unique:
        errors.append("CRITICAL: duplicate participant_id in domain_presence")

    feat = dcount.merge(dpres, on="participant_id", suffixes=("_count", "_pres"))
    df = feat.merge(pid_score, on="participant_id", how="inner")

    df["coverage_breadth"] = df[[f"{c}_pres" for c in DOMAIN_COLS]].sum(axis=1)
    df["evidence_density"] = df[[f"{c}_count" for c in DOMAIN_COLS]].sum(axis=1)

    if "M3_prob" in oof.columns:
        df = df.merge(
            oof[["participant_id", "M3_prob"]],
            on="participant_id", how="left",
        )
    else:
        errors.append("CRITICAL: M3_prob OOF missing from strict_oof file")

    if set(df["participant_id"]) != set(splits["participant_id"].unique()):
        errors.append("CRITICAL: participant_id mismatch with splits")
    if len(df) != 142:
        errors.append(f"CRITICAL: merged n={len(df)}, expected 142")
    if df["participant_id"].duplicated().any():
        errors.append("CRITICAL: duplicate participant_id after merge")
    if df["phq8_score"].isna().any():
        errors.append("CRITICAL: missing PHQ-8 score")
    if df["M3_prob"].isna().any():
        errors.append("CRITICAL: missing M3_prob for some participants")
    if not oof["participant_id"].is_unique:
        errors.append("CRITICAL: duplicate participant_id in strict_oof")
    if "M3_prob" in oof.columns and not oof["M3_prob"].between(0, 1).all():
        errors.append("CRITICAL: M3_prob outside [0,1]")

    if errors:
        for e in errors:
            print("  ", e)
        raise ValueError("Input validation FAILED")

    print(f"[LOAD] OK: n={len(df)}, score range "
          f"{df['phq8_score'].min()}-{df['phq8_score'].max()}, "
          f"positive={int(df['label'].sum())}")
    return df


# ═══════════════════════════════════════════════════════════════════════════
# CROSS-VALIDATED BINARY PREDICTION (fold-local, 10x5 repeated) — reused
# ═══════════════════════════════════════════════════════════════════════════
def run_logistic_cv(df, feature_cols, label_series):
    """Participant-level 10x5 repeated CV for binary logistic regression.
    Returns a Series indexed by participant_id of the mean OOF probability."""
    splits = pd.read_csv(SPLIT_CSV)
    all_probs = []
    for (rpt, fold), fold_rows in splits.groupby(["repeat", "fold"]):
        train_ids = fold_rows[fold_rows["role"] == "train"]["participant_id"].values
        test_ids = fold_rows[fold_rows["role"] == "test"]["participant_id"].values
        train_df = df[df["participant_id"].isin(train_ids)]
        test_df = df[df["participant_id"].isin(test_ids)]
        if len(train_df) == 0 or len(test_df) == 0:
            continue
        Xtr = train_df[feature_cols].values.astype(float)
        ytr = label_series.loc[train_df["participant_id"].values].values
        Xte = test_df[feature_cols].values.astype(float)
        scaler = StandardScaler().fit(Xtr)
        model = LogisticRegression(**LR_PARAMS)
        model.fit(scaler.transform(Xtr), ytr)
        prob = model.predict_proba(scaler.transform(Xte))[:, 1]
        for pid, p in zip(test_df["participant_id"].values, prob):
            all_probs.append({"participant_id": pid, "repeat": rpt, "fold": fold, "prob": p})
    return pd.DataFrame(all_probs).groupby("participant_id")["prob"].mean()


# ═══════════════════════════════════════════════════════════════════════════
# FOUR-GROUP ASSIGNMENT (A/B/C/D) — THIS analysis's operational definition
# ═══════════════════════════════════════════════════════════════════════════
GROUPS = ["A_consistent_high", "B_consistent_low",
          "C_self_high_ev_low", "D_self_low_ev_high"]
GROUP_CN = {
    "A_consistent_high": "A 一致高症状（PHQ高+证据高）",
    "B_consistent_low": "B 一致低症状（PHQ低+证据低）",
    "C_self_high_ev_low": "C 自评高但证据低",
    "D_self_low_ev_high": "D 自评低但证据高",
}
MISMATCH_GROUPS = ["C_self_high_ev_low", "D_self_low_ev_high"]


def assign_four_groups(phq_high, ev_high):
    g = np.full(len(phq_high), "B_consistent_low", dtype=object)
    g[phq_high & ev_high] = "A_consistent_high"
    g[phq_high & ~ev_high] = "C_self_high_ev_low"
    g[~phq_high & ev_high] = "D_self_low_ev_high"
    return g


def error_direction(label, pred):
    """Return array of '低估' / '高估' / '正确'."""
    out = np.full(len(label), "正确", dtype=object)
    out[(label == 1) & (pred == 0)] = "低估"
    out[(label == 0) & (pred == 1)] = "高估"
    return out


# ═══════════════════════════════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════════════════════════════
def main():
    OUTDIR.mkdir(parents=True, exist_ok=True)
    df = load_and_validate()
    label_series = df.set_index("participant_id")["label"]

    # ── Regenerate fold-local OOF (identical procedure to module 12) ─────────
    print("[OOF] Generating fold-local binary OOF predictions (base/count/pres)...")
    feats_base = ["coverage_breadth", "evidence_density"]
    feats_count = feats_base + [f"{c}_count" for c in DOMAIN_COLS]
    feats_pres = feats_base + [f"{c}_pres" for c in DOMAIN_COLS]

    prob_base = run_logistic_cv(df, feats_base, label_series)
    prob_count = run_logistic_cv(df, feats_count, label_series)
    prob_pres = run_logistic_cv(df, feats_pres, label_series)
    prob_complex = df.set_index("participant_id")["M3_prob"]

    oof = pd.DataFrame({
        "participant_id": df["participant_id"].values,
        "label": df["label"].values,
        "phq8_score": df["phq8_score"].values,
        "coverage_breadth": df["coverage_breadth"].values,
        "evidence_density": df["evidence_density"].values,
        "prob_base": prob_base.reindex(df["participant_id"]).values,
        "prob_count": prob_count.reindex(df["participant_id"]).values,
        "prob_pres": prob_pres.reindex(df["participant_id"]).values,
        "prob_complex": prob_complex.reindex(df["participant_id"]).values,
    })
    for m in ["base", "count", "pres", "complex"]:
        oof[f"pred_{m}"] = (oof[f"prob_{m}"] >= THRESHOLD).astype(int)
    # carry the 10 domain count/presence columns so the coding sheet can show
    # which domains are covered / how much evidence each carries (for R1-R6)
    for c in DOMAIN_COLS:
        oof[f"{c}_count"] = df[f"{c}_count"].values
        oof[f"{c}_pres"] = df[f"{c}_pres"].values

    print("[OOF] Sanity AUCs (consistency with modules 11 / 12):")
    for m in ["base", "count", "pres", "complex"]:
        auc = roc_auc_score(oof["label"], oof[f"prob_{m}"])
        print(f"        {m:8s} AUC = {auc:.3f}")

    # ── Four-group assignment (union evidence-high definition) ───────────────
    phq_high = oof["phq8_score"].values >= PHQ_POS_CUT
    ev_high = ((oof["coverage_breadth"].values >= COVERAGE_PREDEF) |
               (oof["evidence_density"].values >= DENSITY_PREDEF))
    oof["_group"] = assign_four_groups(phq_high, ev_high)
    oof["_evidence_status"] = np.where(ev_high, "高", "低")

    # ══════════════════════════════════════════════════════════════════════
    # TABLE 1 — four-group error rates & error directions (QUANTITATIVE)
    # ══════════════════════════════════════════════════════════════════════
    print("[T1] Building four-group error-direction table...")
    models = ["base", "count", "pres", "complex"]
    table_rows = []
    for m in models:
        pred = oof[f"pred_{m}"].values
        lab = oof["label"].values
        direction = error_direction(lab, pred)
        for g in GROUPS:
            mask = (oof["_group"] == g).values
            n = int(mask.sum())
            err = (pred != lab)
            n_err = int(err[mask].sum())
            n_under = int(((direction == "低估") & mask).sum())
            n_over = int(((direction == "高估") & mask).sum())
            er = round(n_err / n, 4) if n else np.nan
            dirs_err = direction[mask][err[mask]]
            if len(dirs_err) == 0:
                main_dir = "—"
            else:
                vc = pd.Series(dirs_err).value_counts()
                main_dir = "—" if (len(vc) > 1 and vc.iloc[0] == vc.iloc[1]) else vc.index[0]
            table_rows.append({
                "model": m, "group": g, "group_cn": GROUP_CN[g],
                "n": n, "n_error": n_err, "error_rate": er,
                "n_underestimate": n_under, "n_overestimate": n_over,
                "main_error_direction": main_dir,
            })
    table_df = pd.DataFrame(table_rows)
    table_df.to_csv(OUTDIR / "attribution_error_direction_table.csv",
                    index=False, encoding="utf-8-sig")

    # ── Mismatch vs consistent error-rate test (Fisher) ──────────────────────
    # Only the Fisher test is retained. In a binary task the error *direction*
    # is fully determined by the label (positive misclassified => underestimate,
    # negative misclassified => overestimate), so a "mismatch-type x direction"
    # chi-square carries little additional information and is omitted.
    print("[STAT] Fisher test (mismatch vs consistent error rate)...")
    stat_rows = []
    for m in models:
        pred = oof[f"pred_{m}"].values
        lab = oof["label"].values
        err = (pred != lab).astype(int)
        mismatch_mask = oof["_group"].isin(MISMATCH_GROUPS).values
        consistent_mask = ~mismatch_mask
        a = int(err[mismatch_mask].sum()); b = int(mismatch_mask.sum() - a)
        c = int(err[consistent_mask].sum()); d = int(consistent_mask.sum() - c)
        if (a + b) > 0 and (c + d) > 0:
            or_f, p_f = scipy_stats.fisher_exact([[a, b], [c, d]])
        else:
            or_f, p_f = np.nan, np.nan
        stat_rows.append({
            "model": m,
            "fisher_or_mismatch_vs_consistent": round(float(or_f), 4) if or_f == or_f else np.nan,
            "fisher_p_mismatch_vs_consistent": round(float(p_f), 4) if p_f == p_f else np.nan,
        })
    stats_df = pd.DataFrame(stat_rows)
    stats_df.to_csv(OUTDIR / "attribution_direction_stats.csv",
                    index=False, encoding="utf-8-sig")

    # ══════════════════════════════════════════════════════════════════════
    # CODING SHEET TEMPLATE — BLANK attribution columns for human reviewers
    # ══════════════════════════════════════════════════════════════════════
    print("[SHEET] Building coding sheets (blank attribution)...")
    mask_mismatch = oof["_group"].isin(MISMATCH_GROUPS).values
    # PRIMARY analysis explains COMPLEX-model errors only (主文只解释 complex 错误);
    # a sample enters the coding pool iff it is a mismatch (C/D) AND complex misclassified it.
    err_ref = (oof["pred_complex"] != oof["label"]).values
    sel = oof[mask_mismatch & err_ref].copy()

    # Apply per-mismatch-type cap (reproducible sampling) and mark selection
    rng = np.random.RandomState(RANDOM_SEED)
    selected_ids = []
    for gt in MISMATCH_GROUPS:
        ids = sel.loc[sel["_group"] == gt, "participant_id"].tolist()
        if len(ids) > CODING_CAP_PER_TYPE:
            picked = rng.choice(ids, size=CODING_CAP_PER_TYPE, replace=False).tolist()
        else:
            picked = ids
        selected_ids.extend(picked)
    sel["selected_for_coding"] = np.where(
        sel["participant_id"].isin(selected_ids), "是", "否").values

    def cn_label(x):
        return "阳性" if x == 1 else "阴性"

    def cn_pred(m):
        return np.where(sel[f"pred_{m}"] == 1, "阳性", "阴性")

    def cn_err(m):
        return np.where(sel[f"pred_{m}"] != sel["label"], "是", "否")

    sheet_base = {
        "participant_id": sel["participant_id"].astype(int).values,
        "phq8_score": sel["phq8_score"].values,
        "phq8_label": sel["label"].apply(cn_label).values,
        "coverage_breadth": sel["coverage_breadth"].values,
        "evidence_density": sel["evidence_density"].values,
        "evidence_status": sel["_evidence_status"].values,
        "mismatch_type": np.where(sel["_group"] == "C_self_high_ev_low",
                                  "PHQ高证据低", "PHQ低证据高"),
        "pred_base": cn_pred("base"),
        "pred_count": cn_pred("count"),
        "pred_pres": cn_pred("pres"),
        "pred_complex": cn_pred("complex"),
        "err_base": cn_err("base"),
        "err_count": cn_err("count"),
        "err_pres": cn_err("pres"),
        "err_complex": cn_err("complex"),
        "n_models_wrong": ((sel["pred_base"] != sel["label"]).astype(int) +
                           (sel["pred_count"] != sel["label"]).astype(int) +
                           (sel["pred_pres"] != sel["label"]).astype(int) +
                           (sel["pred_complex"] != sel["label"]).astype(int)).values,
        "ref_model": "complex",
        "ref_pred": cn_pred("complex"),
        "ref_error_direction": error_direction(sel["label"].values, sel["pred_complex"].values),
        "selected_for_coding": sel["selected_for_coding"].values,
    }
    # 10 domain columns so reviewers can judge R1 (coverage) vs R5 (boundary width)
    for c in DOMAIN_COLS:
        sheet_base[f"{c}_count"] = sel[f"{c}_count"].values
        sheet_base[f"{c}_pres"] = sel[f"{c}_pres"].values
    # BLANK columns for human reviewers (NOT filled by this script)
    for k in ["r1_primary", "r1_secondary", "r1_text", "r1_confidence",
              "r2_primary", "r2_secondary", "r2_text", "r2_confidence"]:
        sheet_base[k] = ""
    sheet = pd.DataFrame(sheet_base)
    # Two outputs: full pool (all mismatch+complex-error rows) + selected subset
    sheet.to_csv(OUTDIR / "coding_pool_all.csv", index=False, encoding="utf-8-sig")
    sheet[sheet["selected_for_coding"] == "是"].to_csv(
        OUTDIR / "coding_sheet_selected.csv", index=False, encoding="utf-8-sig")
    n_c = int((sel["_group"] == "C_self_high_ev_low").sum())
    n_d = int((sel["_group"] == "D_self_low_ev_high").sum())
    n_sel = int((sel["selected_for_coding"] == "是").sum())
    print(f"        mismatch+complex-error pool: C={n_c}, D={n_d}; "
          f"selected for full coding = {n_sel}")

    # ── codebook.md (R1-R6 + procedure) ──────────────────────────────────────
    print("[DOC] Writing codebook.md ...")
    write_codebook()

    # ── Summary markdown (data-driven; Table 1 numbers embedded) ─────────────
    print("[SUM] Writing interpretive summary...")
    manifest = {
        "module": "13_mismatch_error_attribution",
        "created": datetime.now().isoformat(timespec="seconds"),
        "random_seed": RANDOM_SEED,
        "decision_threshold": THRESHOLD,
        "phq_positive_cut": PHQ_POS_CUT,
        "coverage_predef_high": COVERAGE_PREDEF,
        "density_predef_high": DENSITY_PREDEF,
        "evidence_high_definition": "union: coverage_breadth>=5 OR evidence_density>=11",
        "coding_cap_per_type": CODING_CAP_PER_TYPE,
        "n_perm": "n/a (attribution is human-coded)",
        "models": {
            "base": {"type": "logistic_cv", "features": feats_base},
            "count": {"type": "logistic_cv", "features": feats_count},
            "pres": {"type": "logistic_cv", "features": feats_pres},
            "complex": {"type": "external_oof", "source": "07_strict_joint_models/M3_prob"},
        },
        "input_sha256": {
            "domain_count": sha256_file(DOMAIN_COUNT_CSV),
            "domain_presence": sha256_file(DOMAIN_PRESENCE_CSV),
            "splits": sha256_file(SPLIT_CSV),
            "frozen_turns": sha256_file(FROZEN_TURNS),
            "strict_oof": sha256_file(STRICT_OOF_CSV),
        },
        "lr_params": LR_PARAMS,
        "human_attribution": "PENDING — coding_sheet_selected.csv to be filled by "
                             "two independent human reviewers; companion aggregate_coding.py "
                             "produces Table 2 + Cohen's Kappa afterwards.",
    }
    summary_md = build_summary(oof, table_df, stats_df, sel, manifest)
    with open(OUTDIR / "attribution_analysis_summary.md", "w", encoding="utf-8") as f:
        f.write(summary_md)

    # ── Manifests ────────────────────────────────────────────────────────────
    with open(OUTDIR / "run_manifest.json", "w", encoding="utf-8") as f:
        json.dump(manifest, f, ensure_ascii=False, indent=2)

    out_files = [
        "attribution_error_direction_table.csv",
        "attribution_direction_stats.csv",
        "coding_pool_all.csv",
        "coding_sheet_selected.csv",
        "codebook.md",
        "attribution_analysis_summary.md",
        "run_manifest.json",
    ]
    with open(OUTDIR / "output_manifest_sha256.csv", "w", encoding="utf-8-sig") as f:
        f.write("file,sha256\n")
        for fn in out_files:
            p = OUTDIR / fn
            if p.exists():
                f.write(f"{fn},{sha256_file(p)}\n")
    print("[DONE] Module 13 outputs written.")


# ═══════════════════════════════════════════════════════════════════════════
# CODEBOOK
# ═══════════════════════════════════════════════════════════════════════════
def write_codebook():
    txt = """# 错位样本错误归因编码手册（Codebook）

> 模块 13 · DAIC-WOZ PHQ-8 · 本手册供两名独立复核者使用。
> 本分析旨在**描述模型误差的可能来源**，而非对个体真实临床状态作诊断性判断。

## 一、分析对象

依据 PHQ-8 阳性标准（≥10）与预定义高证据切点（覆盖广度 ≥5 **或** 证据密度 ≥11，
二者取并集），样本分为四类：

| 分组 | PHQ-8 自评 | 文本症状证据 | 角色 |
| --- | --- | --- | --- |
| A 一致高 | 高 | 高 | 对照（一致高风险） |
| B 一致低 | 低 | 低 | 对照（一致低风险） |
| C 自评高证据低 | 高 | 低 | 重点错位组 |
| D 自评低证据高 | 低 | 高 | 重点错位组 |

编码对象为 **C、D 两组中复杂模型预测错误的样本**（详见 `coding_sheet_selected.csv` 的
`selected_for_coding=是` 行；完整池见 `coding_pool_all.csv`；若某类过多则按随机种子抽取至多 15 例）。

## 二、复核材料

每名样本提供：
1. 原始访谈文本（由复核者另行调阅，**不写入本仓库**）；
2. 已抽取的访谈文本症状证据（覆盖广度、证据密度、十域计数/是否出现）；
3. PHQ-8 得分、PHQ-8 阳性/阴性标签、模型预测方向与错误方向。

## 三、两轮编码流程

- **第一轮**：复核者仅看访谈文本与症状证据，**不看**模型预测，判断错位原因。
- **第二轮**：加入模型错误方向，判断该归因能否解释错误方向。

两名复核者各自独立填写 `r1_*` 与 `r2_*` 列；分歧经讨论后确定最终归因。
报告一致率或 Cohen's Kappa（由本模块提供的 `aggregate_coding.py` 计算）。

## 四、归因编码表（R1–R6）

| 编码 | 归因类型 | 判断标准 | 常见于 |
| --- | --- | --- | --- |
| R1 | 访谈覆盖不足 | PHQ-8 相关条目在访谈中未被充分询问或展开 | PHQ 高、证据低 |
| R2 | 表达不足或防御 | 被试回答短、回避、否认、缺少症状细节 | PHQ 高、证据低 |
| R3 | 时间窗不一致 | 文本内容不清楚是否对应 PHQ-8 过去两周 | 两类错位均可能 |
| R4 | 负性事件非症状化 | 文本有压力、创伤、关系问题，但不一定构成 PHQ-8 症状 | PHQ 低、证据高 |
| R5 | 证据边界偏宽 | 抽取的症状证据较弱、含糊、非特异 | PHQ 低、证据高 |
| R6 | 自评—访谈通道不一致 | 量表自评与访谈表达明显不一致，无法简单判定谁更准确 | 两类错位均可能 |

> 注意：不要写“被试隐瞒真实症状”这种过于确定的归因；可写“表达不足或防御**可能**”，
> 但不要当作事实。所有自由文本（`r1_text` / `r2_text`）仅填简短、脱敏描述，不得包含
> 可识别个人身份的信息。

## 五、每例填写字段

`participant_id` · `phq8_score` · `phq8_label` · `coverage_breadth` · `evidence_density` ·
`evidence_status` · `mismatch_type` · `pred_*` · `err_*` · `n_models_wrong` ·
`ref_model` · `ref_pred` · `ref_error_direction` · `selected_for_coding` ·
十个症状域的 `*_count` 与 `*_pres`（以上由脚本生成）
+ `r1_primary` / `r1_secondary` / `r1_text` / `r1_confidence` / `r2_primary` / `r2_secondary` /
`r2_text` / `r2_confidence` （由复核者填写；本仓库版本留空）。
"""
    with open(OUTDIR / "codebook.md", "w", encoding="utf-8") as f:
        f.write(txt)


# ═══════════════════════════════════════════════════════════════════════════
# SUMMARY MARKDOWN (data-driven; human attribution noted as pending)
# ═══════════════════════════════════════════════════════════════════════════
def build_summary(oof, table_df, stats_df, sel, manifest):
    L = []
    L.append("# 错位样本错误归因分析（定量部分）")
    L.append("")
    L.append(f"> 模块 13 · DAIC-WOZ PHQ-8 · 分析日期 {manifest['created'][:10]}")
    L.append("> 定量部分来自冻结输入与冻结 10×5 参与者级交叉验证，可复现。")
    L.append("> 人工归因（R1–R6）为待完成项，详见 `coding_sheet_selected.csv` 与 `codebook.md`。")
    L.append("")
    L.append("## 1 四组定义与样本量")
    L.append("")
    L.append("- PHQ-8 高 = 总分 ≥ 10；文本证据高 = 覆盖广度 ≥ 5 **或** 证据密度 ≥ 11（并集，操作性定义，非临床诊断）。")
    L.append("- A 一致高（PHQ高+证据高）· B 一致低（PHQ低+证据低）为对照；C 自评高证据低、D 自评低证据高为错位重点组。")
    for g in GROUPS:
        n = int((oof["_group"] == g).sum())
        L.append(f"  - {GROUP_CN[g]}：n = {n}")
    L.append("")
    L.append("## 2 表 1：四组模型错误率与错误方向（定量）")
    L.append("")
    L.append("| 模型 | 分组 | n | 错误数 | 错误率 | 低估数 | 高估数 | 主要错误方向 |")
    L.append("| --- | --- | --: | --: | --: | --: | --: | --- |")
    for _, r in table_df.iterrows():
        L.append(f"| {r['model']} | {r['group_cn']} | {r['n']} | {r['n_error']} | "
                 f"{r['error_rate']} | {r['n_underestimate']} | {r['n_overestimate']} | "
                 f"{r['main_error_direction']} |")
    L.append("")
    L.append("> 注：二分类任务下错误方向由标签决定（PHQ-8 阳性判错=低估，阴性判错=高估），"
             "故 C 组主方向为低估、D 组主方向为高估是输入—标签冲突方向的**直接体现**，"
             "并非独立统计发现；该表用于呈现错位样本错误的集中与方向，而非方向差异检验。")
    L.append("")
    L.append("## 3 错位—错误关联检验（定量）")
    L.append("")
    L.append("| 模型 | Fisher OR(错位vs一致) | Fisher p |")
    L.append("| --- | --: | --: |")
    for _, r in stats_df.iterrows():
        L.append(f"| {r['model']} | {r['fisher_or_mismatch_vs_consistent']} | "
                 f"{r['fisher_p_mismatch_vs_consistent']} |")
    L.append("")
    L.append("## 4 人工归因（待完成）")
    L.append("")
    L.append("- 错位且预测错误的样本池：C 组 %d 例、D 组 %d 例；建议完整编码 %d 例"
             % (int((sel["_group"] == "C_self_high_ev_low").sum()),
                int((sel["_group"] == "D_self_low_ev_high").sum()),
                int((sel["selected_for_coding"] == "是").sum())))
    L.append("- 编码表：完整池 `coding_pool_all.csv`、待编码子集 `coding_sheet_selected.csv`"
             "（均仅含 ID 与结构化指标，含十域 count/pres，归因列留空）。")
    L.append("- 编码手册：`codebook.md`（R1–R6 + 两轮双复核流程）。")
    L.append("- 填完 `coding_sheet_selected.csv` 后，运行本模块提供的 `aggregate_coding.py` "
             "生成表 2（错位类型 × 主要归因）并计算 Cohen's Kappa。")
    L.append("- 本分析为机制性描述，**不作强因果推断**，不对个体作诊断性判断。")
    L.append("")
    return "\n".join(L)


if __name__ == "__main__":
    main()
