"""Reader-facing tables and global-FDR sensitivity for frozen incremental outputs."""

from __future__ import annotations

from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from .inference import benjamini_hochberg


KEYS = ["embedding", "fusion", "level"]


def add_global_bh(deltas: pd.DataFrame) -> pd.DataFrame:
    """Add one clearly labelled BH q-value over all 16 AUC delta tests.

    This is a sensitivity family only.  It does not overwrite the locked
    primary/secondary q-value columns generated by the formal runner.
    """

    required = {*KEYS, "raw_p"}
    missing = required.difference(deltas.columns)
    if missing:
        raise ValueError(f"delta table is missing required columns: {sorted(missing)}")
    result = deltas.copy()
    if len(result) != 16 or result[KEYS].duplicated().any():
        raise ValueError("global 16-test sensitivity requires 16 unique embedding/fusion/level rows")
    p_values = pd.to_numeric(result["raw_p"], errors="coerce").to_numpy(dtype=float)
    if not np.isfinite(p_values).all() or ((p_values < 0) | (p_values > 1)).any():
        raise ValueError("raw_p must be finite and lie in [0, 1]")
    result["global_bh_q16"] = benjamini_hochberg(p_values)
    result["result_scope"] = np.where(
        result["fusion"].eq("early_concat"),
        "exploratory_early_concat",
        "late_fusion_sensitivity",
    )
    return result


def make_incremental_main_table(
    deltas: pd.DataFrame,
    metrics: pd.DataFrame,
) -> pd.DataFrame:
    """Merge paired delta rows with base/augmented model metrics."""

    delta_table = add_global_bh(deltas)
    required_metrics = {*KEYS, "model_name", "roc_auc", "pr_auc", "brier", "log_loss"}
    missing = required_metrics.difference(metrics.columns)
    if missing:
        raise ValueError(f"metric table is missing required columns: {sorted(missing)}")
    values = metrics.copy()
    values["model_name"] = values["model_name"].astype(str)
    if values.duplicated(KEYS + ["model_name"]).any():
        raise ValueError("metrics must have one row per model and level")
    base = values.loc[values["model_name"].eq("base"), KEYS + ["roc_auc", "pr_auc", "brier", "log_loss"]].rename(
        columns={column: f"base_{column}" for column in ("roc_auc", "pr_auc", "brier", "log_loss")}
    )
    augmented = values.loc[values["model_name"].eq("augmented"), KEYS + ["roc_auc", "pr_auc", "brier", "log_loss"]].rename(
        columns={column: f"augmented_{column}" for column in ("roc_auc", "pr_auc", "brier", "log_loss")}
    )
    table = delta_table.merge(base, on=KEYS, how="left", validate="one_to_one")
    table = table.merge(augmented, on=KEYS, how="left", validate="one_to_one")
    table = table.sort_values(KEYS, kind="stable").reset_index(drop=True)
    return table


def write_markdown_table(table: pd.DataFrame, output_path: str | Path) -> None:
    """Write a compact numeric table without embedding quote-bearing data."""

    destination = Path(output_path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    columns = [
        "embedding",
        "fusion",
        "level",
        "result_scope",
        "base_roc_auc",
        "augmented_roc_auc",
        "delta_auc",
        "auc_ci_low",
        "auc_ci_high",
        "raw_p",
        "bh_q_primary_l4",
        "bh_q_all_late",
        "global_bh_q16",
        "delta_pr_auc",
        "delta_brier",
        "delta_log_loss",
    ]
    present = [column for column in columns if column in table.columns]
    display = table[present].copy()
    for column in display.columns:
        if pd.api.types.is_float_dtype(display[column]):
            display[column] = display[column].map(lambda value: f"{value:.4f}")
    destination.write_text(display.to_markdown(index=False), encoding="utf-8")


def write_report_manifest(table: pd.DataFrame, output_path: str | Path, *, source_files: dict[str, str]) -> dict[str, Any]:
    """Write a small schema/count manifest for the derived reporting table."""

    destination = Path(output_path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    record: dict[str, Any] = {
        "status": "complete",
        "report": "embedding_incremental_reader_facing_tables",
        "n_rows": int(len(table)),
        "n_global_fdr_tests": int(table["global_bh_q16"].notna().sum()),
        "source_files": source_files,
        "result_scope_counts": table["result_scope"].value_counts().to_dict(),
    }
    destination.write_text(pd.Series(record).to_json(indent=2, force_ascii=False), encoding="utf-8")
    return record
